---
- name: Perform the initial setup of the bastion host
  hosts: bastion
  remote_user: root
  vars:
    pf_table_file: "ssh_bruteforce.table"
    pf_table_dir: "/var/db/pf"
  tasks:
    - name: Configure the host's firewall for its bastion role
      block:
        - name: Create the {{ pf_table_dir }} directory when missing
          ansible.builtin.command:
            cmd: "/bin/mkdir {{ pf_table_dir }}"
            creates: "{{ pf_table_dir }}"

        - name: Create the {{ pf_table_file }} file when missing
          ansible.builtin.command:
            cmd: "/usr/bin/touch {{ pf_table_dir }}/{{ pf_table_file }}"
            creates: "{{ pf_table_dir }}/{{ pf_table_file }}"

        - name: Copy the PF configuration file over to the host
          ansible.builtin.copy:
            src: ./files/pf.conf
            dest: /etc/pf.conf
            backup: true
            validate: /sbin/pfctl -n -f %s

        - name: Reload the PF configuration
          ansible.builtin.command:
            cmd: /sbin/pfctl -f /etc/pf.conf

    - name: Apply available OpenBSD patches; store module's return values
      community.general.syspatch:
      register: syspatch_module_retvals

    - name: Output the return values of the syspatch module's run
      ansible.builtin.debug:
        var: output_syspatch_module_retvals
      vars:
        output_syspatch_module_retvals:
          return_code: "{{ syspatch_module_retvals.rc }}"
          stdout: "{{ syspatch_module_retvals.stdout | ansible.builtin.split('\n') }}"
          stderr: "{{ syspatch_module_retvals.stderr | ansible.builtin.split('\n') }}"
          reboot_needed: "{{ syspatch_module_retvals.reboot_needed }}"

    - name: Reboot the host is required to apply the patches
      ansible.builtin.reboot:
      when: syspatch_module_retvals.reboot_needed

    - name: Update all packages installed on the host
      community.general.openbsd_pkg:
        name: '*'
        state: latest
      register: pkg_add_update
