---
all:
  vars:
    ansible_remote_user: cm_user

bastion:
  hosts:
    openbsd:
      ansible_python_interpreter: /usr/local/bin/python3
  vars:
    pf_bruteforce_table_f: "/var/db/pf/ssh_bruteforce.table"

webservers:
  hosts:
    debian:
      ansible_python_interpreter: /usr/bin/python3
    rocky:
      ansible_python_interpreter: /usr/bin/python
