---
infrastructure:
  children:
    jumphost:
    webservers:
  vars:
    ansible_user: cm_user
    ansible_become: true
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: >
      -o PreferredAuthentications=publickey
      -o VerifyHostKeyDNS=yes

jumphost:
  children:
    openbsd:
  vars:
    ansible_become_method: doas
    ansible_python_interpreter: /usr/local/bin/python3

webservers:
  children:
    debian:
    rocky:
  vars:
    ansible_ssh_common_args: >
      -J cm_user@{{ hostvars.bastion.ansible_host }}
      -o PreferredAuthentications=publickey
      -o VerifyHostKeyDNS=yes
#TODO: address the need to duplicate var ansible_ssh_common_args
...
