---
all:
  vars:
    ansible_remote_user: cm_user

ungrouped:
  hosts:
    bastion:
      ansible_python_interpreter: /usr/local/bin/python3
  vars:
    pf_bruteforce_table_f: /var/db/pf/ssh_bruteforce.table

debian:
  vars:
    ansible_python_interpreter: /usr/bin/python3

rocky:
  vars:
    ansible_python_interpreter: /usr/bin/python

webservers:
  children:
    debian:
    rocky:

...
